version: '3.4'

services:
  fice-events-bot:
    image: fictadvisor/fice-events-bot:latest
    command: bash -c "alembic upgrade heads && python bot/main.py"
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - redis
      - postgres
    environment:
      - TOKEN=${TOKEN}
      - POSTGRES_HOST=${POSTGRES_HOST:-fice-events-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - REDIS_HOST=${REDIS_HOST:-fice-events-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - IMGBB_API_KEY=${IMGBB_API_KEY}

  fice-events-redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data

  fice-events-postgres:
    image: postgres:alpine
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}



volumes:
  redis-data:
  postgres-data: