"""Added unique keys

Revision ID: a95323f65935
Revises: ec0c43d32556
Create Date: 2023-04-27 23:43:05.181635

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a95323f65935'
down_revision = 'ec0c43d32556'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_answers_request_id'), 'answers', ['request_id', 'question_id'])
    op.create_unique_constraint(op.f('uq_requests_user_id'), 'requests', ['user_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_requests_user_id'), 'requests', type_='unique')
    op.drop_constraint(op.f('uq_answers_request_id'), 'answers', type_='unique')
    # ### end Alembic commands ###
