"""Added confirm field for request and description for event

Revision ID: ec0c43d32556
Revises: 5e9b9c826a02
Create Date: 2023-04-25 21:06:17.358752

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ec0c43d32556'
down_revision = '5e9b9c826a02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(), nullable=False))
    op.add_column('requests', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'confirmed')
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
